### PR TITLE
Processes.app improvement

### LINKED ISSUE #160: Processes.app improvement
After long test of Processes.app here my todolist

* Migrate totaly to psutils and use **oneshot** and **process_inter** speed up capability
* fit with the OsX Processes Monitor layout
* Create a tabs for CPU/System Memory/Disk/Network
* Have charts graph for CPU 
* Have chart pie for the Memory system
* Create a ToolBar for buttons
* Move the Force button ton the toolbar as original OsX Processes Monitor
* Create a dialog for process inspection, callable by  a Button name **Inspection** on the ToolBar
* Create ListBox with common filter, for a OneClick filter operation
* Create a Input Text for filter on the right of the ToolBar
* Create a dialog for Quit process with 3 buttons: Force Quit -> SIGKILL, Cancel -> Close the dialog, Quit -> SIGTERM
* Optimize the signal queue event system them limit the QT.Timer usage.
* Rename the App **Processes Monitor**
* Link **Processes Monitor** with the Menu.app
* Inform KWin to bind CTRL + ALT + SUPP to a Simplified view Dialog for Kill / Kill -HUP a Process (Like OsX)

Actually i working on:
- [  ] Migrate totaly to psutils and use **oneshot** and **process_inter** speed up capability
- [  ] fit with the OsX Processes Monitor layout
- [  ] Create a tabs for CPU/System Memory/Disk/Network
- [  ] Have charts graph for CPU 
- [  ] Have chart pie for the Memory system
- [  ] Create a ToolBar for buttons
- [  ] Move the Force button ton the toolbar as original OsX Processes Monitor
- [  ] Create a dialog for process inspection, callable by  a Button name **Inspection** on the ToolBar
- [  ] Create ListBox with common filter, for a OneClick filter operation
- [  ] Create a Input Text for filter on the right of the ToolBar
- [  ] Create a dialog for Quit process with 3 buttons: Force Quit -> SIGKILL, Cancel -> Close the dialog, Quit -> SIGTERM

PS: Yes i come from nowhere...

### PR DESCRIPTION
**Pull request by Hierosme**
Fixes #160

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @Hierosme.

Can you please make the About box more like on the other helloSystem utilities (size, icon size, amount and type of text). Thank you.

image

**Comment by probonopd** [comment]
Can we find a way to get the names of the apps with and without icons aligned? (E.g., insert some spacing or a blank icon for the apps without an icon.)

image

**Comment by probonopd** [comment]
In "Disk Activity", what is the difference between "IO" and "Data"?

**Comment by Hierosme** [comment]
> In "Disk Activity", what is the difference between "IO" and "Data"?

psutil have two information's type.

IO == counter increase each time a request Input or Output  is done
DATA == bandwidh in Bytes 

For Network and Disk troubleshooting in general you looking for IO counters

**Comment by Hierosme** [comment]
> Can we find a way to get the names of the processes with and without icons aligned? (E.g., insert some spacing or a blank icon for the processes without an icon.)
> 
> image

i have try a lot to justify the text without success.
A blank image can be a nice solution, but take CPU for nothing.

I finaly have take desision to not burn CPU for nothing, actually the icon management is really mature and got a internal cache system, then YES the blank image will do the job.

**Comment by Hierosme** [comment]
> Thanks @Hierosme.
> 
> Can you please make the About box more like on the other helloSystem utilities (size, icon size, amount and type of text). Thank you.
> 
> image

so bad i like a lot my dialog ... Yes i'll do .

**Comment by Hierosme** [comment]
@probonopd all is done, please make a test, that change make the statup really slow. BUT work.

The trouble is the icon detection for X11 it return a QIcon object, and have have to request is object for know if it the icon is a True one.

that method is OK when you have fews icon, here we have a tonne of icons and a cache have to be create before for evaluate text justification.
.
Each time the appliction start the icon cache create in memory, for fixe the startup slow we should use a cache file and reload when need.

**Comment by louies0623** [comment]
image
Icon I tend to use this one (should be from humanity icon) because it looks like a heartbeat.

**Comment by louies0623** [comment]
> > Can we find a way to get the names of the processes with and without icons aligned? (E.g., insert some spacing or a blank icon for the processes without an icon.)
> > image
> 
> i have try a lot to justify the text without success. A blank image can be a nice solution, but take CPU for nothing.
> 
> I finaly have take desision to not burn CPU for nothing, actually the icon management is really mature and got a internal cache system, then YES the blank image will do the job.

In fact, there is no need for blank space, it is divided into two columns, one column is dedicated to aligning icons, and the other column is dedicated to aligning text.

**Comment by probonopd** [comment]
Well. In fact, we should use the generic "application" icon from the icon theme if there is no other theme for a process.

**Comment by louies0623** [comment]
https://github.com/helloSystem/Artwork/issues/2#issuecomment-1339749512

**Comment by Hierosme** [comment]
I have restore the Icon, and comment the code it cause the slow startup.

To be clear that is not because i dont want code a text justification, or because i not understnd the target.
Qt is the root cause of that trouble.

when Qt not found a Icon it alway set a QIcon() object. Unfortunally for identify if the icon got pixel, it hve request the QIcon object.

If anyone is motivate, and can provide a fixe.
Personally i'll not continue to work anymore on that text justification trouble. i simply havent the require skill.

The code should be merge with it justification trouble, and a issue open...

**Comment by louies0623** [comment]
If the icon is a blank PNG file and 16x16, on the contrary, if you use SVG, it will be really slow.

**Comment by Hierosme** [comment]
Look like that Applications have only minor fixe, from long time ago.

Why not simply merge it and got a users feedback ?

**Comment by Hierosme** [comment]
``` python
                    # Try 1 - Slow, UI Freeze
                    # if QIcon.hasThemeIcon(application_name.lower()):
                    #     icon = QIcon.fromTheme(application_name.lower())
                    # else:
                    #     icon = QIcon(self.icon_empty)

                    # Try 2 - Slow, UI Freeze
                    # icon = QIcon.fromTheme(application_name.lower(), self.icon_empty)

                    # Try 3 - Ultra Slow, big UI Freeze
                    # icon = QIcon.fromTheme(application_name.lower(), self.icon_empty)
                    # if icon.isNull():
                    #     icon = QIcon(self.icon_empty)

                    # Try 4 - Acceptable speed, no UI Freeze
                    icon = QIcon.fromTheme(application_name.lower())
```

**Comment by louies0623** [comment]
@Hierosme We have to remove the icons! I'm sorry I didn't see the source of the image clearly, that's a copyright icon, this one was created by humanity-icon.
utilities-system-monitor

SVG file

**Comment by Hierosme** [comment]
That is done cher

**Comment by probonopd** [comment]
Do you think this is ready for merge?
Thanks @Hierosme

**Comment by Hierosme** [comment]
Yes that is time cher.

Open issue should be the way for any change from now ...

**Comment by Hierosme** [comment]
Hope helloSystem users and developpers will have a nice system monitor tool.
Typically a Core tool native to hellSystem.

I have make it with love and all hight skill level focus to Power Saving.
Just yake a look how that tool have ultra low CPU usage ... :dancers: 

Enjoy !!! :tada:

**Comment by probonopd** [comment]
Thank you very much @Hierosme.
I have added you to

**Comment by louies0623** [comment]
PNG
utilities-system-monitor
---------
process-stop info clock

Please change the three icons and the icon of the program. I have converted them to PNG, which can reduce performance consumption.

**Comment by Hierosme** [comment]
> ## PNG
> utilities-system-monitor
> process-stop info clock
> 
> Please change the three icons and the icon of the program. I have converted them to PNG, which can reduce performance consumption.

Unfortunally you should open a new Issue about Processes.app icon. (i'll do)
I'll do it sure ....

I like a lot the icons set

**Comment by louies0623** [comment]
I'm in the latest development preview version to test your Processes, and it's currently working fine. It's just that when I scroll with the mouse, my CPU will be occupied by 25%, and scrolling up and down quickly will occupy 70%.  And the button part is as shown in the picture, it would be better if it can be in the lower right corner instead of the lower left corner.

**Comment by probonopd** [comment]
Indeed, buttons should go to the right hand side.

**Pull request merged**
