### PR TITLE
Do not keep asking for password when adjusting date and time (fix #165)

### LINKED ISSUE #165: [PC-1-screen0.webm](https://github.com/helloSystem/Utilities/assets/44593430/842ecf81-1344-41e7-890f-6f45d0c15910)
[PC-1-screen0.webm](https://github.com/helloSystem/Utilities/assets/44593430/842ecf81-1344-41e7-890f-6f45d0c15910)

Need to fix the bug that keeps asking for the password when adjusting the date and time

_Originally posted by @louies0623 in https://github.com/helloSystem/Utilities/issues/163#issuecomment-1600610846_

### PR DESCRIPTION
**Pull request by Hierosme**
Fixe #165

### CODE REVIEW

**Comment by probonopd** [comment]
If possible please use our UI font, Nimbus Sans, for the clock face. Thanks!

**Comment by Hierosme** [comment]
> If possible please use our UI font, Nimbus Sans, for the clock face. Thanks!

Its Done for the Clock Face. (From Roboto to Numbus Sans)
I suspect you want the AM/PM font too ? i have do it just in case ...

**Comment by probonopd** [comment]
Thank you very much. Yes, let's use Nimbus Sans in all places, never Noto.

**Comment by probonopd** [comment]
This pull request contains at least 3 apps. It would be better to have one pull request for each application. Thanks!

**Pull request closed without merging**
