### PR TITLE
Fix the Network app

### PR DESCRIPTION
**Pull request by linuxkettle**
This code is meant to fix helloSystem/Menu#23 by changing the way it calls wpa_cli.

You can see that FeatherPad is a bit agressive about trailing whitespace, so a lot of the patch is just removing whitespace from the end of the lines.

### CODE REVIEW

**Comment by probonopd** [comment]
> This code is meant to fix helloSystem/Menu#23 by changing the way it calls wpa_cli.

Hello @linuxkettle, thanks for the PR. What exactly does it try to "fix"? Can you give a concrete example of what was not working before that is working now? Thanks.

**Comment by linuxkettle** [comment]
Okay, I've converted everything to QProcess. I tested it, and it let me connect to the WiFi at my house (WPA2 Personal) - I haven't tried Enterprise but that should work anyways.

I also fixed a FIXME where you can't see the icon very well, the solution is quite simple: use the Network.png icon bundled in the applet.

As for strength showing in the icon, I have not done that, but that is an enhancement and beyond the scope of this PR.

**Comment by linuxkettle** [comment]
Okay, thank you for that.
The code uses QProcess now, and I've made a battery-status-icon branch that adds a battery status icon.

My system tray is looking nice and healthy now!

**Comment by probonopd** [comment]
Looks great, but oddly it displays only some of the available networks.
This was also the case before your changes, and is also the case when running

```
wpa_cli scan
wpa_cli scan_results
```

This shows my neighbors' networks but not mine... I haven't figured out yet why.

Also, please make 2 minor changes:
* The icon in the menubar needs to be black/grey, not blue. Icons in the menu are supposed to be monochrome unless they communicate somehting urgent, e.g., a failure
* Please do not use the world "WiFi" as it is trademarked. Always use "network", "wireless network". "WLAN" (or nothing) instead.

**Comment by linuxkettle** [comment]
Okay, I've fixed those two things.
> This shows my neighbors' networks but not mine...

That's very strange indeed. Might you be using WEP?  
At my house the neighbors' network shows up above my one, but they

**Comment by probonopd** [comment]
Something with the icon does not seem right now:

image

**Comment by probonopd** [comment]
While we are at it, we should also make it possible to left-click the icon to bring up the menu, like it is done here:

https://github.com/anaynayak/buildnotify/pull/194/files

**Comment by linuxkettle** [comment]
That's weird, does QIcon not support SVG?

It should look like this:
image

**Comment by linuxkettle** [comment]
> While we are at it, we should also make it possible to left-click the icon to bring up the menu, like it is done here:

I see the problem. `setContextMenu` sets the right click menu you usually see in a text field with copy, paste etc. You need to connect the activated signal to the show slot on the menu for left click to work.

**Comment by probonopd** [comment]
Now the menu appears on a left click but not at the correct position on screen. (On my screen, it appears in the upper-left corner of the screen.) Hence need to use QCursor as shown in https://github.com/anaynayak/buildnotify/pull/194/files.

The correct icon is not shown, as in my screenshot.

**Comment by linuxkettle** [comment]
Oh yes, I see now. I'm going to look further into the icon issue, I think I'll need to scale it to a PNG because it uses the exact same method as the blue icon of looking for it in the Resources folder, the only difference I can see is SVG.

**Comment by probonopd** [comment]
We should also put in something like

https://github.com/helloSystem/Utilities/commit/0a893b52a3d81047c4dfa5b1773e32df65166bdd

so that users get an error dialog if no wireless device is found, along with a recommended (known working) one.

**Comment by probonopd** [comment]
Merged since it's clearly an improvement; let's open new tickets for the remaining issues.

**Pull request merged**
