### PR TITLE
Add Network Utility.app 

### PR DESCRIPTION
**Pull request by Hierosme**
Implements #112

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @Hierosme.

Please make the About dialog more like the About dialogs of the other helloSystem utilities, as I have described in https://github.com/helloSystem/Utilities/pull/190#issuecomment-1694212442.

And please check all spelling.

**Comment by Hierosme** [comment]
> Thanks @Hierosme.
> 
> Please make the About dialog more like the About dialogs of the other helloSystem utilities, as I have described in [#190 (comment)](https://github.com/helloSystem/Utilities/pull/190#issuecomment-1694212442).
> 
> And please check all spelling.



> Thanks @Hierosme.
> 
> Please make the About dialog more like the About dialogs of the other helloSystem utilities, as I have described in [#190 (comment)](https://github.com/helloSystem/Utilities/pull/190#issuecomment-1694212442).
> 
> And please check all spelling.

Yes i'll do, but i like a lot my About dialog ...

**Comment by probonopd** [comment]
I understand, but at least for the utilities coming with the operating system by default, we should have a unified look and feel. Makes the whole thing more professional.

**Comment by Hierosme** [comment]
i'll survive :+1:

**Comment by Hierosme** [comment]
Done

**Comment by Hierosme** [comment]
It can be merge into master branch , then permit user feedback.

**Comment by probonopd** [comment]
Thanks @Hierosme.

It would be nice to have a tab that can find all other network devices on the same network. Especially useful for those devices that don't use Zeroconf.

Example:
"How can I access the webcam I just put into my network?"

**Pull request merged**
