### PR TITLE
Check to see if our installer script is executable

### PR DESCRIPTION
**Pull request by xaoseric**
Checks to see if the installer script is executable, makes it executable if it is not.

### CODE REVIEW

**Comment by probonopd** [comment]
hello @xaoseric 

> Checks to see if the installer script is executable

Very good, thank you

> makes it executable if it is not

Can you make print an error to stderr, and exit with code 1?
An application should not modify itself due to security considerations.

**Comment by xaoseric** [comment]
@probonopd done, it should now exit with code 1 and print a message to stderr

**Comment by probonopd** [comment]
Thank you @xaoseric

**Comment by probonopd** [comment]
Need to revert since this shows an error even though `/usr/local/bin/furybsd-install` is available and is executable on the helloSystem ISO.

**Comment by xaoseric** [comment]
It is checking for `furybsd-install` not for `/usr/local/bin/furybsd-install`

**Comment by probonopd** [comment]
Yes; it needs to accept the installer script being present in either of the possible locations.

**Pull request merged**
