### PR TITLE
Major updates: interface improvements, new icon, new UI elements, new keyboard shortcuts, usability improvements

### PR DESCRIPTION
**Pull request by TriVoxel**
Remade the application icon to look less... "meth-ey", no offense lol. Re-designed the user interface with a clean, modern symbolic design. These are original designs by me, so no need to fuss about copyright. Added a new tab button. Added the ability to press CMD+L to get into the URL bar. Added the keyboard shortcut to reload the page with CMD+R. It is also available through the File menu. You can now re-organize your tabs and sort them as you please!

Simple Browser

Going forward, I'd like to add a preferences pane, search engine integration, cookies, private browsing, "open link in new tab", and more! Need help getting cookies up and running, if you don't mind!

### CODE REVIEW

**Comment by TriVoxel** [comment]
I'd like to add a preferences pane with search engine functionality and cached file & cookie settings. Would be nice to be able to type a search term and for it to automatically search the web. We should also have a download tray.

**Comment by TriVoxel** [comment]
@probonopd If you wouldn't mind helping me understand how to get cookies working with QWebEngine, I'd really appreciate it. I want to have a standard web browsing mode and a private one. I'm trying to follow the documentation but I'm having a hard time getting it to work with PyQt5. Perhaps it's my lack of knowledge on the subject. Anyways, hope you like the work I've done here.

**Comment by probonopd** [comment]
Thanks for your work on Simple Browser. I hadn't coded this one from scratch, but just lightly changed an existing piece of software, so I can't tell you much on its inner workings.

Regarding cookies, maybe this is helpful?
https://doc.qt.io/archives/qt-5.10/qtwebengine-webenginewidgets-cookiebrowser-example.html

**Comment by probonopd** [comment]
Will merge once I have a chance to test, may take a few days.

**Comment by TriVoxel** [comment]
> Thanks for your work on Simple Browser. I hadn't coded this one from scratch, but just lightly changed an existing piece of software, so I can't tell you much on its inner workings.
> 
> Regarding cookies, maybe this is helpful? https://doc.qt.io/archives/qt-5.10/qtwebengine-webenginewidgets-cookiebrowser-example.html

Thanls for the reference. I'll take a look at it. I'm going to be doing some major code refinements for future developents. At the end of it all, it will be a complete and new browser.

**Comment by probonopd** [comment]
@TriVoxel do you think I should merge this PR as-is, or are you planning on making more changes in the next days/weeks?

**Comment by TriVoxel** [comment]
@probonopd go ahead and merge this. I may not be able to contribute for a while longer, and these improvements will make it a much better experience, albeit a still incomplete one.

**Comment by TriVoxel** [comment]
@probonopd Hey, looks like you forgot to review this. Hope things are going well. Can't wait to hear what you think about these improvements. I may think about adding more features down the line if you like what you see.

**Comment by probonopd** [comment]
Thank you very much @TriVoxel and sorry it took so long to review and merge.
Also thanks for the reminder.

**Pull request merged**
