### PR TITLE
Calculator  + Activity Monitor  + Network Utility

### PR DESCRIPTION
**Pull request by Hierosme**
## Calculator v0.2rc1
* Still FixedSize but with a size management
* Spanning col/row for 0 and =
* Introduse memory line MC, M+, M-, MR
* Introduse ± key
* Fit with layout of OsX
* Use true operator symbol and convert them before the eval
* Add CHANGELOGSD file

## Activity Monitor v0.2rc1 (Fork of Process.app)
* Migrate totaly to psutils and use oneshot and process_inter speed up capability
* fit with the OsX Processes Monitor layout
* Create a tabs for CPU/System Memory (Disk / Disk usage / Network still empty)
* Create a ToolBar for buttons
* Move the Force button ton the toolbar as original OsX Processes Monitor
* Create ListBox with common filter, for a OneClick filter operation
* Rename the App Activity Monitor

### CODE REVIEW

**Comment by probonopd** [comment]
Hi @Hierosme. Please don't rename apps without discussion first, as this would break things.

And please run everything through a good spellchecker.
Thanks!

**Comment by Hierosme** [comment]
I have revert my commit it rename a App.
Now that is a fork inside Under Construction directory.

Activity Monitor take me time due to FreezeUI it require Qthead usage and detached Worker's.
The CPU Graph will certainly require to create a Plot Widget from scratch (Then take more time)

but still in the way.

**Comment by probonopd** [comment]
Impressive progress. Please let me know once you think this is ready to be merged.

**Comment by Hierosme** [comment]
that is not ready but i share some screen shoot.

YES the screen is not from helloSystem, due to my test about cross platform, yes the Activity Monitor is trully cross platform.

The chart pie Widget and color Picker are home made.

image

image

Actually i focus to implement Signals and ultra low power usage for everything it update data in the Application.

The code is make with love to be a strong compagnon in  the hello System Desktop.

Enjoy...

**Comment by Hierosme** [comment]
Hello,

Some news about the Activity Monitor:

- Every Tabs have been convert to .ui file and Custum Widget continue to work .
- Low power thing by never write a value if not really need. (1000 reads for one write rule...)
- About dialog for confim Kill and Send signal have been add

That is almost ready for tests...

What it still have to be done:

- CPU Graph history dialog
- Network Graph
- Disk activity Graph
- Translation
- Inspection Processe dialog

**Comment by Hierosme** [comment]
What have been all ready done
- Migrate totaly to a .ui (qtdesigner)
- I just have add Icon support for helloSystem. ( based on a internal cache system.)
- Icon support work with X11 theme search capability
- Filter Windowed process is specific to helloSystem (Only the true BUMDLE app)

Next step:
- Finish Inspection Dialog
- Add Graph for Disk Activity Tab
- Add Graph for Network Tab

The code is testable on helloSystem and/or Linux (But certain option work only under helloSyem)

**Comment by Hierosme** [comment]
Note Icons Management and .app application name.
image

image

**Comment by probonopd** [comment]
Thank you very much @Hierosme. I will test it as soon as possible.
Am interested in others' reviews as well.

**Review by probonopd — CHANGES_REQUESTED** [review]
Please move the contents of `qressources.qrc` directly into the /Resources directory so that a `.qrc` file is not needed. This makes editing and managing those files easier.

**Comment by probonopd** [comment]
Do you think you could work on Disk Utility? I think it is the most missing piece of helloSystem utilities at the moment.

**Comment by Hierosme** [comment]
> Please move the contents of `qressources.qrc` directly into the /Resources directory and load them from there (without Qt resources) so that a `.qrc` file is not needed. This makes editing and managing those files easier.

Certainly.

I have almost finish the Network Utility, i can continue with Disk Utility

**Comment by Hierosme** [comment]
> Please move the contents of `qressources.qrc` directly into the /Resources directory and load them from there (without Qt resources) so that a `.qrc` file is not needed. This makes editing and managing those files easier.

It have been done...

**Comment by probonopd** [comment]
> I have almost finish the Network Utility, i can continue with Disk Utility

That would be very, very useful. Thanks for your contributions!

**Review by probonopd — APPROVED** [review]

**Comment by probonopd** [comment]
Please let me know how you would be credited on https://hellosystem.github.io/docs/developer/acknowledgements.html. If you would like me to use your real name, please give me a hint. Thanks!

**Comment by probonopd** [comment]
Where are the icons coming from, what license are they under? Thanks.

**Comment by Hierosme** [comment]
> Where are the icons coming from, what license are they under? Thanks.

That icon is a error where i have store a icon with the same name.

The icon is from scratch by me. the license is same as the Activity monitor.

If i remenber i have keep the Processes.app icon, because the icon look good but confuse to me.
I can restore the Processe.app iconif you like, other else look like the random life got use a icon for activity Monitor.

PS: My bad , tell me if you want i restore the Processes.app.

**Comment by probonopd** [comment]
> The icon is from scratch by me. the license is same as the Activity monitor.

Then it is OK. Thank you very much.

**Comment by Hierosme** [comment]
I'll impose that icon for GNU/Linux let me fews minutes ...

**Comment by Hierosme** [comment]
> I'll impose that icon for GNU/Linux let me fews minutes ...

Done, Activity Monitor have it own identity.

@probonopd No trouble you can use my real name (that the frist time), in general i change name each time i contribute to a new project. Please use RealName alias **Tuuux** as my gitlab. https://gitlab.com/Tuuux/

**Comment by Hierosme** [comment]
OK without any response i'll add custum code for deal with icon location dynamically. (Because that was the direction of the code review). I'll fixe that today.

**Comment by Hierosme** [comment]
It is done and test under helloSystem and GNU/Linux

**Comment by Hierosme** [comment]
Network Utility have been add for preview.

Actually that is not a MainWindow widget then it have no menu.
The tools require to install **dig** and **nmap**. (it take a entire life to code nmap)

The design is done arround QProccess Class and it work very well.

Like the original Network Utility that use the true system command , the interface is just a View.

No freeze at all, the info tab refresh with a Thread, **Low Tech but good Tech**

Any feedback are welcome

THEN let see the Disk Utility .....

**Comment by Hierosme** [comment]
Unfortunally my DEV Station is under GNU/Linux and **geom** is BSD specific .... look like Disk Utility must be devellop nativelly under helloSystem.

I have never succes to install helloSytem under VirtualBox (The global menu crash ans that finish), then i simply can't make anything serius for Disk Utility with my Dev Station.

Sorry, i really has take a look, but many thing are OS specific.

From my point without a True Python Disk Mangement BSD backend it will be very hard to have a real stable tool.

**Comment by probonopd** [comment]
Looking good. I am impressed with Activity Monitor. :+1

* Please delete my old Processes.app and rename/move Activity Monitor to Processes.app (in the same location as my old Processes.app was)
* Please delete my old Calculator.app rename/move your version to replace mine (in the same location as my old Processes.app was)
* Please remove all version numbers from both applications (we don't version each application separately, just the overall git repository)
* In the "Sample Process" and "Inspect" window, what does the "Quit" button do? Kill the process, or just close the window? If the latter, then it should be called "Close" instead
* "All right reserved." is missing a "s"

Then I can merge it and the next continuous helloSystem ISO build should have it (not "Under Construction" but as the real default applications).

Since it is still newer, I suggest that we leave Network Monitor in "Under Construction" for a while. Impressive work here as well.

* In Network Monitor, File -> Quit does not work yet
* In Network Monitor, we should add an About box similar to the ones in my utilities. It should mention the command line tools used (like in Keyboard.app)
* Can you add a tab that would scan the local network for devices, similar to the code I had posted? (My use case: I have added a new smart home device to the network but it doesn't advertise its IP address with Zeroconf, and I don't know under which IP address I can access its configuration page.)

Thank you very much!

**Comment by Hierosme** [comment]
Everything is done:

- [ x ] delete my old Processes.app and rename/move Activity Monitor to Processes.app (in the same location as my old Processes.app was)
- [ x ] delete my old Calculator.app rename/move your version to replace mine (in the same location as my old Processes.app was)
- [ x ]  remove all version numbers from both applications
- [ x ] Rename Process.app Inspection and Sample dialog Quit buttons to Close
- [ x ]  "All right reserved." is missing a "s"
- [ x ] Network Monitor, File -> Quit does not work yet
- [ x ] Process and Network Monitor, got a About box similar to other utilities. )


About the Port Scan
Actually you can scan you entire network (and more) with the Port Scan Tab by enter an jocker char "*" by example 192.168.42.*. How imagine that ... the LineEdit is pass directlly to nmap. If you have something to tell to nmap do not hesitate .... :0)

The big trouble is the need of root privilege for OS detection and other good option (-o -sS).

Yes i can add a new tab but i prefert add the two options you need in the actual Port Scan tab...

ps: poor Network Utility, too young ... that is a injustice for it ...
ps2: that is tested helloSystem and  GNU/Linux the mush i can.

**Comment by probonopd** [comment]
About the port scan, my use case is that someone who doesn't know anything about now tools like `nc` work can just press one button and see which devices are up in the local network (`*.*.*.255`). Should be simple to use.

**Comment by Hierosme** [comment]
Yes agrea, the Port Scan is powerfull because i know how to use Nmap and iḿ the rare gui who know the QLineEdit can be use as normal like CLI. 
I have show the Network Utility to other Dev and each time my use of the LineEdit is a surprise. Power full but totally un commun....

The Network Utility have been fast to devellop because the backend was out of the scope. All my work consit to use nmap over a QProcess and speck with it over signals.

1)
Sorry for the next part. My job daily job is arround Network .

2)
The MAC reverse lookup is call OUI protocol (https://en.wikipedia.org/wiki/Organizationally_unique_identifier)

In fact we have to integrate all they contructor list:
http://standards-oui.ieee.org/oui/oui.txt
http://standards-oui.ieee.org/oui28/mam.txt
http://standards-oui.ieee.org/oui36/oui36.txt
http://standards-oui.ieee.org/iab/iab.txt

Greate a big dataset , and make a search inside ....
Some Python module all ready make it job...

3)
I really not want to creat from scratch a Scanner Backend, especially because it have to be maintain over the time.

I totaly understand you need, in general i go to my DHCP lease in that case, but you speack about a user story where the user can be in front of a Unversal Discover Tool.

4)
 The propose of Network Utility is network troubleshooting clearly not a unversal network discover.

That type of technology is totaly not the original approch of nmap.
In general a discover is base on Multicast and Broadcast , where nmap (at first) scan host by host , that nean Unicast.

Look a implementation:
https://github.com/julienblitte/UniversalScanner
https://www.microfocus.com/en-us/products/configuration-management-system-database/overview

The original issue #112 just speack about a nmap GUI. Then by design, when i have think about the Network Utility, i have focus to let nmap (and other tools) make they work.

5)
A Universal Discovers System is really special  it couple UPNP, Bonjour, ZeroConf, Scan Unicast , Scan Group Multicast, Zigbee, Bluetooth LE, Z-Wave,  LoRa and more if needed .... It type of scanner is common IoT

You can do the search by you self Port Scan is just a micro part of the job.
https://arxiv.org/abs/2204.02538

Summry:
I undestand you user storie, i really understand...  but to me it look like 10 years full time job, i can confirme to you.
I havent the time to create a Universal Network Discovery, and just the idea to maintain it over the time stop me in place.

My job is just base on the #112.
the code is OpenSource (And i'll help you), you can make a try ...

**Comment by Hierosme** [comment]
Sorry for my long silence i just have take a vacation breack.

do i split it PR for got one PR by App ?

i propose to create 3 branchs like ADD/NetworkUtility.app, REMAKE/Process.app, UPDATE/Calculator.app.
Then create PR from they branchs in to Master. That should reach the requirement.

by the way:
a good practice consitit is to merge code almost in continue, then not wait to have a big monolitic  PR. The goal is to limit the delta and got more control during the integration phase. Not like integration continue, but more like a integration as fast and small as possible ... a step on the road in to direction of continus integration.

Regards

**Comment by probonopd** [comment]
Welcome back @Hierosme, yes, please do make one PR for each app. Thanks!

**Pull request closed without merging**
